// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZCcuj-7X1p3PIET-HNe-VODnn9LvgG4',
    appId: '1:13656167112:web:a3389b915ea21ba9fb4bfd',
    messagingSenderId: '13656167112',
    projectId: 'iliganongo-8e5b7',
    authDomain: 'iliganongo-8e5b7.firebaseapp.com',
    storageBucket: 'iliganongo-8e5b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAklq8nSfTYNTCIgxOXsCUROZY_gtjW-JA',
    appId: '1:13656167112:android:cfad4718a4f1d0e6fb4bfd',
    messagingSenderId: '13656167112',
    projectId: 'iliganongo-8e5b7',
    storageBucket: 'iliganongo-8e5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6WiD7MaUzV8riBxnpcGuKOlKziWPQkOc',
    appId: '1:13656167112:ios:b6ab14966d2f42b3fb4bfd',
    messagingSenderId: '13656167112',
    projectId: 'iliganongo-8e5b7',
    storageBucket: 'iliganongo-8e5b7.firebasestorage.app',
    iosBundleId: 'com.tigley.iliganonGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6WiD7MaUzV8riBxnpcGuKOlKziWPQkOc',
    appId: '1:13656167112:ios:b6ab14966d2f42b3fb4bfd',
    messagingSenderId: '13656167112',
    projectId: 'iliganongo-8e5b7',
    storageBucket: 'iliganongo-8e5b7.firebasestorage.app',
    iosBundleId: 'com.tigley.iliganonGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhZCcuj-7X1p3PIET-HNe-VODnn9LvgG4',
    appId: '1:13656167112:web:e043bc31f9dc2797fb4bfd',
    messagingSenderId: '13656167112',
    projectId: 'iliganongo-8e5b7',
    authDomain: 'iliganongo-8e5b7.firebaseapp.com',
    storageBucket: 'iliganongo-8e5b7.firebasestorage.app',
  );

}


